workflows:
  ios-release:
    name: iOS Release (IPA)
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      flutter: 3.27.0
      xcode: latest
      cocoapods: 1.16.2

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.example.megatourApp

    scripts:
      # =========================
      # 1. Flutter prepare
      # =========================
      - name: Flutter clean & pub get
        script: |
          flutter clean
          flutter pub get

      # =========================
      # 2. iOS Pod install (FIX ALL FLUTTER/PLUGIN ISSUES)
      # =========================
      - name: iOS pod install
        script: |
          cd ios
          rm -rf Pods Podfile.lock .symlinks Flutter/Flutter.framework Flutter/Flutter.podspec
          pod install --repo-update
          cd ..

      # =========================
      # 3. Build IPA
      # =========================
      - name: Build IPA
        script: |
          flutter build ipa \
            --release \
            --export-options-plist=ios/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        apple_id: your_apple_id@email.com
        password: $APP_STORE_CONNECT_PASSWORD
