workflows:
  ios-workflow:
    name: iOS Flutter Build
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      flutter: 3.16.9
      xcode: 15.0
      cocoapods: default

      vars:
        IOS_BUNDLE_ID: "com.example.megatour"

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - name: Flutter clean & pub get
        script: |
          flutter clean
          flutter pub get

      - name: iOS full clean (IMPORTANT)
        script: |
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          rm -rf ios/.symlinks
          rm -rf ios/Flutter/Flutter.framework
          rm -rf ios/Flutter/Flutter.podspec

      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build iOS (no codesign)
        script: |
          flutter build ios --no-codesign --debug

    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
