platform :ios, '13.0'

flutter_root = ENV['FLUTTER_ROOT']

unless flutter_root
  raise "FLUTTER_ROOT not set. Run pod install via Flutter tools."
end

require File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper')

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
